name: Atualizar Documentação
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update documentation
        run: python automation.py
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update documentation"
          git push origin main
